resource_group_name = "new-resource-group"
location = "eastus"
service_plan_name = "new-service-plan"
os_type = "Linux"
sku_name = "F1"
web-app-name = "new-web-app"
storage_account_name = "new-storage-account"